---

- name: install git
  yum: name=git



- fail: msg='Please configure the config.yml first!'
  when: not SSH_PASSWORD or not GITHUB_USER or not GITHUB_PASSWORD

- name: create ssh folder
  file: path=~/.ssh state=directory

- stat: path=~/.ssh/github_ansible_generated
  register: sshkey
  changed_when: false

- name: generate ssh key - skip if it's already exist
  command: "ssh-keygen -t rsa -b 4096 -N '{{SSH_PASSWORD}}' -f ~/.ssh/github_ansible_generated"
  when: not sshkey.stat.exists

- name: copy public key
  command: "cat ~/.ssh/github_ansible_generated.pub"
  register: sshpublickey
  changed_when: false

- name: add public key to github account
  uri:
    url: https://api.github.com/user/keys
    method: POST
    user: "{{GITHUB_USER}}"
    password: "{{GITHUB_PASSWORD}}"
    body: "{\"title\":\"ansible_generated_{{ansible_user_id}}@{{ansible_hostname}}\",\"key\":\"{{sshpublickey.stdout}}\", \"_hack\": null}"
    force_basic_auth: yes
    body_format: json
    status_code: 201, 422 #201 - set key, 422 - key is already in use
